---
# Conntracct Example Configuration

# HTTP API endpoint.
api_enabled: true
api_endpoint: "localhost:8000"

# Accounting probe configuration.
probe:
  # Update rate interval. rate_curve has 3 configurable curve points.
  #
  # When a flow is older than the age of the first curve point, it will send updates
  # at the configured rate. In this example, all flows start out at one event per 20 seconds.
  # Once it reaches the age of the next curve point (60 seconds), it will send updates
  # once every 60 seconds, etc.
  rate_curve:
    0:
      age: 0
      rate: 20s
    1:
      age: 60s
      rate: 60s
    2:
      age: 5m
      rate: 5m

# Data Sinks (outputs)
sinks:
  influxdb_udp:
    type: influxdb-udp
    address: "localhost:8089"
    batchSize: 200
    # sourcePorts: false   # (default: false) log connections' (usually-)random source ports
    # udpPayloadSize: 512  # (default: 512) only change this on local networks within MTU

  influxdb_http:
    type: influxdb-http
    address: "http://localhost:8086"
    database: conntracct_http
    batchSize: 200
    # sourcePorts: false

  elastic:
    type: elastic
    address: "http://localhost:9200"  # comma-separated list of elasticsearch server URLs
    # database: conntracct   # (default) index prefix (results in 'conntracct-YYYY.MM.DD')
    # shards: 3              # (default) amount of shards to use for indices
    # replicas: 0            # (default) amount of replicas to use for indices
    # username: my-username  # basic HTTP auth username
    # password: my-password  # basic HTTP auth password

  dummy:
    type: dummy

# Automatically configure necessary sysctls for Conntrack.
sysctl_manage: true

# Run a pprof endpoint during operation.
pprof_enabled: false
pprof_endpoint: "localhost:6060"
